version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - asset_net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - asset_net

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - asset_net
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A AssetsMgrToyProjectInternal worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    networks:
      - asset_net
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A AssetsMgrToyProjectInternal beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - celery_worker
      - db
      - redis
    networks:
      - asset_net
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  asset_net: