version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      # pg로 시작하는 이름은 불가
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypw
      POSTGRES_DB: mydb
    ports:
      # 외부에 노출시킬 포트 : 내부 포트
      - "5432:5432"
