# Generated by Django 5.2.4 on 2025-07-24 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='종목 코드 (예: AAPL, 005930)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='회사명', max_length=200)),
                ('market', models.CharField(help_text='시장 (KOSPI, KOSDAQ, NASDAQ 등)', max_length=50)),
                ('sector', models.CharField(blank=True, help_text='업종', max_length=150, null=True)),
                ('industry', models.CharField(blank=True, help_text='산업군', max_length=150, null=True)),
                ('listed_at', models.DateField(blank=True, help_text='상장일', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='현재 거래 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '종목 기본 정보',
                'verbose_name_plural': '종목 기본 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='보유 수량', max_digits=20)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, default=0, help_text='평균 매수 단가', max_digits=20)),
                ('buy_date', models.DateField(blank=True, help_text='최초 매수일', null=True)),
                ('note', models.TextField(blank=True, help_text='비고 / 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_assets', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_assets', to='stock.stockinfo')),
            ],
            options={
                'verbose_name': '보유 종목',
                'verbose_name_plural': '보유 종목 목록',
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='StockInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_by_users', to='stock.stockinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interestsed_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '관심 종목',
                'verbose_name_plural': '관심 종목 목록',
                'db_table': 'stock_interest',
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
