# Generated by Django 5.2.4 on 2025-07-24 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='종목 코드 (예: AAPL, 005930)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='회사명', max_length=200)),
                ('market', models.CharField(help_text='시장 (KOSPI, KOSDAQ, NASDAQ 등)', max_length=50)),
                ('sector', models.CharField(blank=True, help_text='업종', max_length=150, null=True)),
                ('industry', models.CharField(blank=True, help_text='산업군', max_length=150, null=True)),
                ('listed_at', models.DateField(blank=True, help_text='상장일', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='현재 거래 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '종목 기본 정보',
                'verbose_name_plural': '종목 기본 정보 목록',
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='뉴스 제목', max_length=255)),
                ('content', models.TextField(help_text='뉴스 본문')),
                ('source', models.CharField(help_text='뉴스 제공자', max_length=100)),
                ('url', models.URLField(blank=True, help_text='뉴스 원문 링크', null=True)),
                ('published_at', models.DateTimeField(help_text='기사 작성 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stock.stockinfo')),
            ],
            options={
                'verbose_name': '주식 뉴스',
                'verbose_name_plural': '주식 뉴스',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='해당 거래 날짜')),
                ('open_price', models.DecimalField(decimal_places=2, default=0, help_text='해당 날짜의 시가', max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, default=0, help_text='해당 날짜의 종가', max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, default=0, help_text='해당 날짜의 고가', max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, default=0, help_text='해당 날짜의 저가', max_digits=12)),
                ('volume', models.BigIntegerField(default=0, help_text='해당 날짜의 거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터 수정 일시')),
                ('stock', models.ForeignKey(help_text='해당 히스토리가 속한 주식', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stock.stockinfo')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(help_text='캔들 시간')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='시가', max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='고가', max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='저가', max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='종가', max_digits=12)),
                ('volume', models.BigIntegerField(help_text='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='stock.stockinfo')),
            ],
            options={
                'verbose_name': '주식 차트',
                'verbose_name_plural': '주식 차트',
                'ordering': ['-datetime'],
                'unique_together': {('stock', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='보유 수량', max_digits=20)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, default=0, help_text='평균 매수 단가', max_digits=20)),
                ('buy_date', models.DateField(blank=True, help_text='최초 매수일', null=True)),
                ('note', models.TextField(blank=True, help_text='비고 / 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_assets', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_assets', to='stock.stockinfo')),
            ],
            options={
                'verbose_name': '보유 종목',
                'verbose_name_plural': '보유 종목 목록',
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='StockInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_by_users', to='stock.stockinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interestsed_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '관심 종목',
                'verbose_name_plural': '관심 종목 목록',
                'db_table': 'stock_interest',
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
