# Generated by Django 5.2.4 on 2025-07-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['date'], 'verbose_name': '주식 이력', 'verbose_name_plural': '주식 이력'},
        ),
    ]
