# Generated by Django 5.2.4 on 2025-07-24 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockasset',
            options={'verbose_name': '보유 종목', 'verbose_name_plural': '보유 종목 목록'},
        ),
        migrations.AddField(
            model_name='stockasset',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='평균 매수 단가', max_digits=20),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='buy_date',
            field=models.DateField(blank=True, help_text='최초 매수일', null=True),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='note',
            field=models.TextField(blank=True, help_text='비고 / 메모', null=True),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='보유 수량', max_digits=20),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_assets', to='stock.stockinfo'),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stockasset',
            unique_together={('user', 'stock')},
        ),
    ]
