# Generated by Django 4.2.5 on 2025-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KosDaQDDInFor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bas_dd", models.CharField(max_length=8)),
                ("isu_cd", models.CharField(max_length=100)),
                ("isu_nm", models.CharField(max_length=100)),
                ("mkt_nm", models.CharField(max_length=100)),
                ("sect_tp_nm", models.CharField(max_length=100)),
                ("tdd_clsprc", models.BigIntegerField()),
                ("cmpprevdd_prc", models.BigIntegerField()),
                ("fluc_rt", models.FloatField()),
                ("tdd_opnprc", models.BigIntegerField()),
                ("tdd_hgprc", models.BigIntegerField()),
                ("tdd_lwprc", models.BigIntegerField()),
                ("acc_trdvol", models.BigIntegerField()),
                ("acc_trdval", models.BigIntegerField()),
                ("mktcap", models.BigIntegerField()),
                ("list_shrs", models.BigIntegerField()),
            ],
            options={
                "db_table": "kosdaq_dd_info",
            },
        ),
        migrations.CreateModel(
            name="KospiDDInFor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bas_dd", models.CharField(max_length=8)),
                ("inx_clss", models.CharField(max_length=100)),
                ("idx_nm", models.CharField(max_length=100)),
                ("clsprc_idx", models.BigIntegerField()),
                ("cmpprevdd_idx", models.BigIntegerField()),
                ("fluc_rt", models.FloatField()),
                ("opnprc_idx", models.BigIntegerField()),
                ("hgprc_idx", models.BigIntegerField()),
                ("lwprc_idx", models.BigIntegerField()),
                ("acc_trdvol", models.BigIntegerField()),
                ("acc_trdval", models.BigIntegerField()),
                ("mktcap", models.BigIntegerField()),
            ],
            options={
                "db_table": "kospi_dd_info",
            },
        ),
    ]
