# Generated by Django 4.2.5 on 2025-02-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AsStock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExChangeBsInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bas_dd", models.CharField(max_length=8)),
                ("bas_ymdhms", models.CharField(max_length=14)),
                ("ex_Base", models.CharField(max_length=10)),
                ("ex_Rates", models.FloatField()),
            ],
            options={
                "db_table": "exchangeBsInfo",
            },
        ),
        migrations.CreateModel(
            name="GoldByDDInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bas_dd", models.CharField(max_length=8)),
                ("lsu_cd", models.CharField(max_length=100)),
                ("lsu_nm", models.CharField(max_length=100)),
                ("tdd_clsprc", models.BigIntegerField()),
                ("cmpprevdd_prc", models.BigIntegerField()),
                ("fluc_rt", models.CharField(max_length=100)),
                ("tdd_opnprc", models.BigIntegerField()),
                ("tdd_hgprc", models.BigIntegerField()),
                ("tdd_lwprc", models.BigIntegerField()),
                ("acc_trdvol", models.BigIntegerField()),
                ("acc_trdval", models.BigIntegerField()),
            ],
            options={
                "db_table": "gold_by_dd_info",
            },
        ),
        migrations.CreateModel(
            name="InterestRateInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bas_dd", models.CharField(max_length=8)),
                ("bas_ymdhms", models.CharField(max_length=14)),
                ("ir_Base", models.CharField(max_length=10)),
                ("ir_Rates", models.FloatField()),
            ],
            options={
                "db_table": "interestRateInfo",
            },
        ),
        migrations.CreateModel(
            name="OilByDDInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bas_dd", models.CharField(max_length=8)),
                ("oil_nm", models.CharField(max_length=100)),
                ("wt_avg_prc", models.CharField(max_length=256)),
                ("wt_dis_avg_prc", models.CharField(max_length=256)),
                ("acc_trdvol", models.BigIntegerField()),
                ("acc_trdval", models.BigIntegerField()),
            ],
            options={
                "db_table": "oil_by_dd_info",
            },
        ),
    ]
